version: "3"
services:
  srv:
    restart: unless-stopped
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./files:/var/www/public/files
      - ./srv/Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
  api:
    restart: unless-stopped
    build: api
    ports:
      - "8080:80"
    volumes:
      - ./files:/var/www/public/files
